### ISSUE TITLE
popup issue

### ISSUE THREAD

**Issue by chawyehsu** [lisonge/Disable-CSP#1]
popup 点开显示这样，导致点不了开关。浏览器是 Edge 116，尝试过关掉所有其它扩展，没变化。
![image](https://github.com/lisonge/Disable-CSP/assets/5764917/13918845-27ff-46a3-8ede-fdb04ea87fcb)

**Comment by lisonge** [comment]
好的，我已复现，感谢反馈

**Comment by lisonge** [comment]
edge/chrome 商店已提交审核, 也可以手动安装 <https://github.com/lisonge/Disable-CSP/releases/tag/v1.0.3>
